project:
  type: book

book:
  title: "Convex Optimization"
  sidebar:
    style: floating
    pinned: true
    collapse-level: 2
    contents:
      - index.qmd
      - section:  "Introduction"
        contents:
          - introduction/intro.qmd

      - section: "Convex Sets"
        contents:
          - convex-sets/convex-set.qmd


      - section: "Convex Functions"
        contents:

