project:
  type: website
  output-dir: docs

website:
  title: "Kim Hung Bui"
  site-url: https://kimhungbui.github.io
  description: "My Personal Website"
  navbar:
    left:
      - href: index.md
        text: Home
      - href: cv.md
        text: Resume
      - mathematic.md
      - artificial-intelligent.md
      - programming.md
      - english.md
      - posts.md

    right:
      - icon: rss
        href: posts.xml
  google-analytics: "G-R5TB4V4ZYS"



format:
  html:
    theme:
      light: flatly
      dark: darkly
    toc: true
