project:
  type: website
  output-dir: docs

website:
  title: "Kim Hung Bui"
  site-url: https://kimhungbui.github.io
  description: "My Personal Website"
  navbar:
    left:
      - href: index.md
        text: Home
      - href: cv.md
        text: Resume
      - href: mathematic.md
        text: Mathematics
      - href: artificial-intelligent.md
        text: AI
      - href: programming.md
        text: Programming
      - href: english.md
        text: English
      - href: posts.md
        text: Posts

    right:
      - icon: rss
        href: posts.xml

  google-analytics: "G-R5TB4V4ZYS"

format:
  html:
    theme:
      light: flatly
      dark: darkly
    toc: true
