project:
  type: website
  output-dir: docs

website:
  title: "Kim Hung's ThinkStack"
  site-url: https://kimhungbui.github.io
  description: "My Personal Website"
  navbar:
    left:
      # - href: index.md
      #   text: Home
      - href: cv/cv.qmd
        text: Resume
      - text: Mathematics
        menu:
          - text: Convex Optimization
            href: math/convex-optimization/
          - text: Probability
            href: math/probability/
          - text: Statistics
            href: math/statistics/
      - href: artificial-intelligent.md
        text: AI

      - href: programming.md
        text: Programming

      - href: english.md
        text: English
      - href: posts.md
        text: Posts

    right:
      - icon: rss
        href: posts.xml

  google-analytics: "G-R5TB4V4ZYS"

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    footnotes-hover: true
    code-copy: true
    code-link: true
    code-overflow: wrap
    fig-align: center
    link-external-icon: false
    link-external-newwindow: true
    email-obfuscation: javascript
    include-in-header: "files/includes/_academic.qmd"
