---
title: Transitive Verb an Intransitive Verb
lightbox: false
description: Your post description
author:
  - name: Hung
    url: https://kimhungbui.github.io
date: 2025-04-16
categories:
  - english
  - grammar
draft: false
---
A transitive verb is a verb that requires an object to receive the action.


> [!Example] Example
> Correct: The speaker __discussed__ _different marketing strategies_ in the video.
> Incorrect: The speaker __discussed__ in the video.
> The verb "discuss" requires an object ("different marketing strategies"). It is necessary to state that the speaker discussed.

__Example Sentences:__

Some other examples of transitive verbs are "address," "borrow," "bring," "discuss," "raise," "offer," "pay," "write," "promise," and "have."

- The instructor __addressed__ _the student's_ question.

- Miriam __borrowed__ _the methodology book_ from her classmate because she forgot her copy.

- Can you __bring__ _your copy of the textbook_ to our study group meeting?

- The committee members __will raise__ _money_ for the new project.

## Direct and Indirect Objects

A transitive verb can take more than one object.

- Donovan __gave__ ___his sister___ _a laptop_.

In this sentence, there is an indirect object, "his sister," and a direct object, "a laptop." However, there is another way to say this same idea using a prepositional phrase.

- Donovan __gave__ _a laptop_ to his sister.
In English, an indirect object may come between a transitive verb and the direct object, as the first example sentence about Donovan, or the indirect object could be in the form of a prepositional phrase, like the second example sentence about Donovan.

An indirect object is only needed if the action is being done to or for somebody, when using a transitive verb, we need to include a direct object, but we may not need to include in indirect object.

## Finding the object

We can figure out the object by using the question format: "The subject did what?" or "The subject 'verb' what?"
	The instructor __addressed__ what
	_the student's question_

Miriam __borrowed__ what?
_the methodology book_

Can you __bring__ what?
_your copy of the textbook_

The speaker __discussed__ what?
_different marketing strategies_

The committee members __will raise__ what?
_money_

We can find the indirect by asking the question "To whom?" or "For whom?"

Donovan __gave__ _a laptop_ to whom?
_his sister_

# Intransitive Verbs

An intransitive verb does not take an object. Using an object immediately after an intransitive verb will create an incorrect sentence. However, there may be other information after the verb, such as one or more prepositional phrases or an _adverb_.


> [!Example] Example
> Correct: The students __arrived__ at the residency in Houston.
> Incorrect: The students __arrived__ _Houston_.

The second sentence is incorrect because the verb cannot take an object.

__Example Sentences__

Some other examples of intransitive verbs are "deteriorate", "vote", "sit", "increase", "laugh", "originate", "fluctuate", and "trend".

> The patient's health __deteriorated quickly__.
> Ahmad __voted__ in the local election.
> May I __sit _here___
> Attendance **increased** at the weekly study sessions as finals drew near.
> Susan __laughed__.

Note: An intransitive verb can take more than one prepositional phrase of adverb.

> The patient's health __deteriorated _quickly___ _during the night_.
> Ahmad __voted__ _for the incumbent_ in the local election.


# Verbs That Are Both Transitive and Intransitive

Some verbs can be both transitive and intransitive, depending on the situation. In some instances, such a verb may require an object, while in others it does not require an object.

__Example Sentences__

Format reminder: __verb__, _object_, ___propositional phrase___, `adverb`.

__continue__

> We will __continue__ _the meeting_ after the break. (transitive)
> The meeting __continued__ ___after the break___. (intransitive)

__play__
> Three of the students __play__ _the guitar_. (transitive)
> The students will __play__ `outside today`.

 __return__
 > Javier __returned__ _the book_ to the library. (transitive)
> The students __returned__ ___to school___ __after the winter break___. (intransitive)

__grow__

> I __grow__ _zucchini_ in my garden. (transitive)
> My daughter __is growing__ `quickly`. (intransitive)




