---
title: Singular or Plural?
lightbox: false
description: When plural
author:
  - name: Hung
    url: https://kimhungbui.github.io
    affiliation: Pauline Cullen
    affiliation-url: 
date: 2025-07-29
categories:
  - english
format:
  html:
    toc: true
    toc-location: right
    number-sections: true
    number-depth: 3
    code-fold: true
    highlight-style: a11y
draft: false
---
# Tick the correct sentence in each pair.
1. a There are several problem with this idea.
   b There are several problems with this idea.
   -> b
2. a Many charity organizations provide a great deal of help
   b Many charity organization provides a great deal of help
   ->a

If we use a plural noun, we must use a plural verb. The verb must 'agree' with the noun:

_In my country, __there are__ very few __cars__ that use leaded petrol._ (plural verb + plural noun)

_I like studying during the day but __my friend prefers__ studying at night._ (singular noun + singular verb)

We use a plural noun with:
- plural verbs: _are, were, have, do, play, etc._: There are a lot of books on the table.
- numbers greater than one: 30 cars, 100 students
- _many_: It is annoying that so __many buses drive__ fast because they __are__ full.
- _the number of_: __The number of buses__ on our roads __has__ increased each year.

Note that we use a plural noun but a singular verb after _the number of_

We use a singular noun with:
- singular verbs: _is, was, has, does, plays, etc._: There is only one bedroom in the flat.
- _a/an_ or _one_: a car, one student

Note that some nouns can look plural but are singular (_news, mathematics_) and some nouns have a different form in the plural (_children, men, women, people_)

# Correct the mistake below

The number of woman studying science increased dramatically last year.

The number of women studying science increased dramatically last year.

# Underline the correct word in each sentence.

1. The children are playing in the street.
2. The number of men studying science has decreased.
3. There are a lot of people in my class.
4. I enjoyed studying mathematics a lot; I found it very interesting
5. The news was very upsetting.
6. How many classes do you have today?
7. A person I really admire is my uncle.
8. My father watches a lot of sport on TV.

# Which nouns don't have a plural form?

Tick the correct sentence in each pair

1 a I don't have many time to complete my assignment
b I don't have much time to complete my assignment 

-> a 

2 a When I did a search on my computer, I could only find a few informations about the topic.

b When I did a search on my computer, I could only find a little information about the topic.

-> b

Some nouns in English are 'uncountable'. This means they do not have a plural form. Some common uncountable nouns are: _advice, advertising, food, furniture, garbage, information, knowledge, money, shopping, time, traffic, travel_

With uncountable nouns, you must see:

- the singular form: _food, information, money_
- _a little / amount of / much / some_: How <font color="#00b050">much money</font> do you have?
  The <font color="#00b050">amount of traffic</font> on the roads is increasing each year.
- a singular verb: There <font color="#00b050">was</font> already a little <font color="#00b050">furniture</font> in the flat.

If a noun is uncountable, you cannot use:

-  a plural form: ~~advices, furnitures, garbages, informations, knowledges ~~
- a/an: ~~an advice, a garbage, a knowledge~~
- a few / many / number of: ~~a few shopping, many traffie, the number of knowledge~~
- a number: ~~three travels, four furniture~~
- a plural verb: ~~There were a little furniture in the flat.~~

If we want to add a number to an uncountable noun, we can use _a piece of / some / a few pieces of_: <font color="#00b050">a piece of advice, three pieces of furniture, a few pieces of garbage</font>


## Tick the correct sentence in each pair