---
title: Type of collocations
lightbox: false
description: Do exercises and extend
author:
  - name: Hung
    url: https://kimhungbui.github.io
    affiliation: Cambridge Advance Grammar in Use
    affiliation-url: 
date: 2025-08-08
categories:
  - english
format:
  html:
    toc: true
    toc-location: right
    number-sections: true
    number-depth: 3
    code-fold: true
    highlight-style: a11y
draft: false
---
There are many different types of collocation. Here are some examples

# Adjectives and nouns

Notice adjectives that are typically used with particular nouns.

Emma always wears red or yellow or some other __bright color__.

We had a __brief chat__ about the exams but didn't have time to discuss them properly.

Unemployment is a __major problem__ for the government at the moment.

Improving the health service is another __key issue__ for government.

# Nouns and Verbs

Notice how nouns and verbs often go together. The examples below are all to do with economics and business.

The economy boomed in the 1990s. (the economy was very strong)

The company has grown and now employs 50 more people than last year.

The company has expanded and now has branches in most major cities.

The two companies merged in 2013 and now form one very large corporation.

The company launched the product in 2012.

The price increase __poses a problem__ for us.

The internet has created opportunities for our business.

