---
title: "Expressing and reporting opinions: it-clauses"
lightbox: false
description: Do exercises and extend
author:
  - name: Hung
    url: https://kimhungbui.github.io
    affiliation: Cambridge Advance Grammar in Use
    affiliation-url: 
date: 2025-07-27
categories:
  - english
  - grammar
format:
  html:
    toc: true
    toc-location: right
    number-sections: true
    number-depth: 3
    code-fold: true
    highlight-style: a11y
draft: false
---
# Expressing opinions impersonally

In academic communication, we tend to be impersonal, focusing more on actions, we effects of actions, and the things affected by actions rather than the people performing the actions. We often use _it-_ clauses to express opinions impersonally in academic writing and speaking. Common patterns here:

___it_ + be (adverb) + adjective + _to-_ infinitive__

e.g. __It is extremely difficult to evaluate__ the role of tourism in urban renewal.

:::{.column-margin}
_Other adjectives_ commonly used in this pattern: __(in)convenient, easy, hard, important, (im)possible, interesting, (un)necessary, (un)reasonable, (in)sufficient, useful__
:::

___it_ + be + (adverb) + adjective + _that___

__It is quite possible that__ a larger sample size would have shown different results.

:::{.column-margin}
_Other adjectives_ commonly used in this pattern: __apparent, (un)clear, (in)conveivable, doubtful, essential, evident, important, (un)likely, obvious, probable, true__
:::

Note that not all adverbs and adjectives in these patterns can combine. For example, we commonly use __quite + possible/ clear__, nut rarely __quite + doubtful/ essential__

We often use a passive verb form in an __it- clause__ with __that__ when we report another person's opinion. Notice that we usually include a reference to the other person's work, often immediately after the reporting verb or at the end of the sentences:

__It has been reported__ (Crane, 2015) __that__ prolonged periods sitting in front of a computer may have significant health risks.

:::{.column-margin}
Verbs commonly used in this pattern:  
**argue&#42;**, **claim&#42;**, **contend&#42;**, **demonstrate**, **estimate**, **maintain&#42;**, **note**, **propose&#42;**, **report&#42;**, **show**, **suggest&#42;**
:::

# Distancing yourself from a point of view
We often use an __it-clause__ when we want to distance ourselves from an earlier point of view, perhaps because it is now disputed, or because we feel there was some limitation or problem with the earlier work:

__It has been claimed that__ cheese intake is associated with high cholesterol levels (Zemel, 2001), but more recent studies have found that cheese may even have a cholesterol lowering effect (Hamedi, 2018; Allen, 2019)

__It is often suggested that__ air pollutants from traffic, such as nitrogen oxide (NO2) and suspended particulate matter have a negative impact on child health (e.g. Janssen, 2004, Knape 2012). However, relatively few studies so far have looked at the health of children living near busy roads.

The reporting verbs mark * in Above margin note are often used in this way.

# Disagreeing
In academic contexts we often begin a disagreement by acknowledging that some part of the opposing position is true. _Its-clauses_ are often used for this in academic writing and also in spoken academic contexts (presentation, seminars, etc.)

__It is sometimes argued that__ it is important for students to outline their essays before beginning writing (e.g. Cotton, 2004). While __it is quite correct that__ much of an essay can be planned in advanced, __it must also be noted that__ the act of writing itself facilities thought and shapes ideas.

__It's often assumed that__ environmental sustainability and poverty reduction can go hand-in-hand. Although __it's certainly possible to find__ a small number of examples where this happens, in most cases in the literature __it is reported that__ the costs of environmental improvement fall on the poor rather than the wealthy.

However, in less formal spoken contexts we sometimes prefer more personal forms. For example: __We often assume that ..., ... you can certainly find ...__.

# Exercises

## Complete the sentences using an impersonal it-clause starting with a phrase from (i), that or a to-infinitive from (ii), and an ending from (iii). For questions 5 and 6 use your own ideas to complete the sentences

| (i)              | (ii)              | (iii)                                                       |
| ---------------- | ----------------- | ----------------------------------------------------------- |
| it is likely     | that              | a number of other approaches are possible.                  |
| it is doubtful   | that              | human activity is the cause.                                |
| it is important  | that              | it is missing from the school curriculum in many countries. |
| it is easy       | to tell           |                                                             |
| it is impossible | to see            | why homeowners are concerned with energy efficiency.<br>    |
| it is surprising | to recognize that |                                                             |
1. Given the high cost of electricity and gas, <font color="#00b050">it is easy to see why homeowners are concerned with energy efficiency</font>.
2. The general views is that the Earth's climate is warming, and <font color="#00b050">it is likely that human activity is the cause</font>.
3. Educationalists have been advocating the importance of critical thinking for many years, so <font color="#00b050">it is surprising that it is missing from the school curriculum in many countries</font>. 
4. Although the approach outlined above will be used in this research, <font color="#00b050">it is important to recognize that a number of other approaches are possible</font>.
5. Because little research has so far been done on the new drug, <font color="#00b050">it is impossible to tell how effective it will be in treating hearth disease</font>.
6. The report recommends diverting more state funding from roads to railways, but it is doubtful that it is enough for the project. / but it is doubtful that the present government would be willing to do this.

## Complete each example using a quotation from the box. Begin your answer with an it-clause and a reporting verb in the passive. Choose from the reporting verbs marked * in the box in section A opposite.

"Aromatherapy can cure recurring headaches." (Majid, 2016)
"Domestic technology has decreased the amount of time spent on housework." (Hill, 2010)
"Research output can be measured by number of papers published". (Hirsch, 2018)
"Voting in general elections should be made compulsory." (Chen, 2005)
"Plants have intelligence." (Glass, 2018)

1. I<font color="#00b050">t has been proposed that voting in general elections should be made compulsory (Chen, 2005)</font>. There would, however, be considerable public opposition to this move.
2. <font color="#00b050">It has been ~~claimed~~ -> contend that plants have intelligence (Glass, 2018)</font>, although as they do not have a nervous system, they cannot form thoughts.
3. <font color="#00b050">It has been claimed that domestic technology has decreased the amount of time spent on housework (Hill, 2010)</font>, but as Burr (2014) points out, this is true only in the most developed countries.
4. <font color="#00b050">It has been reported that aromatherapy can cure recurring headaches (Majid, 2016)</font>. Nevertheless, there is little evidence that the treatment works in the long term.
5. <font color="#00b050">It has been argued by Hirsch (2018) that research output can be measured by number of papers published</font>. However, this does not take into account co-authorship of research articles.

## Use it-clauses and the phrases in the box below to comple the extract from an academic presentation, following the pattern in section C opposite.

<font color="#00b050">It's sometimes maintained</font> that a top-down management style is preferable because it allows clear goals and expectations to be set. <font color="#00b050">It is undoubtedly true</font> that in this type of organization, employees are not distracted from their work by participating in the decision-making process. However, <font color="#00b050">it's important to recognize</font> that many innovations start at the grassroot level in companies rather than at management level.

Some possible ways of making the it-clauses less impersonal:

It is sometimes maintained that ... - Some people say/ think that ...

It is undoubtedly true that ... - I agree/ accept that ...

It is important to recognize ... - We also need to accept that ...