---
title: Lesson 14
lightbox: false
description: Structure
author:
  - name: Hung
    url: https://kimhungbui.github.io
    affiliation: Pauline Cullen
    affiliation-url:
date: 2025-10-04
categories:
  - english
format:
  html:
    toc: true
    toc-location: right
    number-sections: true
    number-depth: 3
    code-fold: true
    highlight-style: a11y
draft: false
---
Use a different grammatical structure. Some useful examples of this are: changing a verb to a

noun; changing from active to passive; changing the focus of a sentence e.g. by making the object

of the sentence into the subject; or by beginning with the final idea. Look at the grammatical

changes I needed to make just by reversing the ideas in this sentence and changing the verb ‘to study’ into a noun:

- It is better to study overseas than in your home town .

- Studying in your home town has fewer advantages than studying overseas.


1 Although celebrities have problems, there are plenty of advantages to being famous.

-> Despite the benefits that fame brings, celebrities still have their problems.

2 Although celebrities have problems, there are plenty of advantages to being famous.
(words to use: however; benefits; bring)

Fame brings plenty of benefits, however, being celebrity also have its problems.

3 All primary school children should be taught a foreign language
(compulsory; curriculum)

Learning a foreign language should be a compulsory part of the primary school curriculum.

4 Children should learn a foreign language in primary school instead of high school.
(better; rather)

It is better for children to learn a foreign language in primary school rather than in high school.


Being able to speak a second language is very useful.

-> Some people argue that it is more beneficial / helpful to start this type of study at primary school instead of secondary school.

-> Some people believe that it is best to do this at primary school instead of waiting until secondary school.

-> Some people believe that beginning this type of study earlier than secondary school is beneficial to students.

-> Some people believe that being taught such a skill earlier than secondary school is beneficial to students.



***

The <> speak <> language is useful <>. However, <> some debate over <> age to learn a new language, with some, experts believing that this <> at <> . In my view, <> little <> starting.


<> to learning a foreign language early in life. The brains of young children are often compared to sponges <> ability to soak up knowledge. <> learn languages far more easily <> lack the self-consciousness <> interfere with language learning at high school, <> can be reluctant to make pronunciation mistakes in front of <> . <>, primary school students are happier to take risks <>, can have fun with <> learning. <> mastering a language takes a long time, <> to see <> recommend starting <>.

Nevertheless, there are several challenges to introducing a second language <>. Firtsly, <>, primary school students <> one teacher <>. This means the staff <> teach a foreign language. Secondly, <> in a child's education; they <> the basics of literacy and numeracy <>. Thus, teachers do not have the time to <> words and phrases in another language. Furthermore, by <> , students <> of their mother tongue, which <> language. In fact, <> with first language acquisition. Therefore. the disadvantages <>.

In conclusion, there <> be limited <> studying a foreign language <> very <>, and <> <> these. <> school years <> stress-free <> children; adding <> their curriculum is <> after that for <>.