name: Render and Publish
on:
  push:
    branches:
      - main  # changes pushed to this branch will trigger a build.

jobs:
  build-deploy:
      runs-on: ubuntu-latest
      permissions:
        contents: write
      steps:
        - name: Check out repository
          uses: actions/checkout@v3
          
        - name: Set up Quarto
          uses: quarto-dev/quarto-actions/setup@v2
          with:
            version: 1.5.57

        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: '3.10'  # Choose a stable version

        - name: Install Python dependencies
          run: |
            python -m pip install --upgrade pip
            pip install nbformat jupyter plotly pandas matplotlib scikit-learn
            # Add any other packages needed by your Quarto document
            
        - name: Publish to GitHub Pages (and render)
          uses: quarto-dev/quarto-actions/publish@v2
          with:
            target: gh-pages # rendered html files will be pushed here
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # this secret is always available for github actions