name: Render and Publish

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: 1.5.57

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install nbformat jupyter plotly pandas matplotlib scikit-learn
      
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install TinyTeX via R
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-latex-base
          Rscript -e 'install.packages("tinytex", repos = "https://cloud.r-project.org")'
          Rscript -e 'tinytex::install_tinytex()'

      - name: Render all books
        run: |
          # Automatically find all book projects and render them
          find . -name "_quarto.yml" | while read qfile; do
            dir=$(dirname "$qfile")
            if grep -q "type: *book" "$qfile"; then
              echo "Rendering book: $dir"
              quarto render "$dir"
            fi
          done

          # Finally render the main website
          quarto render .


      - name: Publish to GitHub Pages
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          path: docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
